-- CreateEnum
CREATE TYPE "TipoCampeonato" AS ENUM ('PONTOS_CORRIDOS', 'PONTOS_CORRIDOS_ELIMINATORIAS', 'ELIMINATORIAS');

-- AlterTable
ALTER TABLE "Campeonato" ADD COLUMN     "tipo" "TipoCampeonato" NOT NULL DEFAULT 'PONTOS_CORRIDOS';
