ALTER TABLE "SetPartida"
ADD COLUMN "gamesA" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "gamesB" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Placar"
ADD COLUMN "setsContra" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "diferencaSets" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "gamesPro" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "gamesContra" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "diferencaGames" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "pontosPro" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "pontosContra" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "diferencaPontos" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "pontosAverage" DOUBLE PRECISION NOT NULL DEFAULT 0;
